export const companyData = 
[
		{
			sponsorName: "YHills",
			webp: "sponsors/silver/webp/yhills.webp",
			// src: "./assets/PowerSponsors/yhils.png",
			url: "https://yhills.com/",
			src : "https://res.cloudinary.com/ds7xs3pq1/image/upload/v1672681953/yhills_qtgadh.png",
			id: "silver_0",
		},
		{
			sponsorName: "Celo",
			webp: "sponsors/silver/webp/celo.webp",
			src: "https://res.cloudinary.com/ds7xs3pq1/image/upload/v1672682010/celo_bypcar.png",
			url: "https://celo.org/",
			id: "silver_1",
		},
		{
			sponsorName: "Filecoin",
			webp: "sponsors/silver/webp/filecoin.webp",
			src: "https://res.cloudinary.com/ds7xs3pq1/image/upload/v1672682042/filecoin_trex6t.png",
			url: "https://filecoin.io/",
			id: "silver_2",
		},
		{
			sponsorName: "Tezos",
			webp: "sponsors/silver/webp/tezos.webp",
			src: "https://res.cloudinary.com/ds7xs3pq1/image/upload/v1672682062/tezos_xizy3k.png",
			url: "https://tezos.com/",
			id: "silver_3",
		},
		{
			sponsorName: "Github",
			webp: "sponsors/silver/webp/github.webp",
			src: "https://res.cloudinary.com/ds7xs3pq1/image/upload/v1672682083/github_fphxpw.png",
			url: "https://www.github.com/",
			id: "silver_4",
		},
		{
			sponsorName: "Stickermule",
			webp: "sponsors/silver/webp/stickermule.webp",
			src: "https://res.cloudinary.com/ds7xs3pq1/image/upload/v1672682114/stickermule_ejcgdg.png",
			url: "http://hackp.ac/mlh-stickermule-hackathons",
			id: "silver_5",
		},
		{
			sponsorName: "Leading learners",
			webp: "sponsors/silver/webp/leadinglearners.webp",
			src: "https://res.cloudinary.com/ds7xs3pq1/image/upload/v1672682144/leadinglearn_asuhf8.webp",
			url: "https://www.leadlearners.ca/",
			id: "silver_6",
		},
		{
			sponsorName: "Coding Blocks",
			webp: "sponsors/silver/webp/codingblocks.webp",
			src: "https://res.cloudinary.com/ds7xs3pq1/image/upload/v1672682166/cblogo_jvwkzg.png",
			url: "https://codingblocks.com/",
			id: "silver_7",
		},
		{
			sponsorName: "Coding Minutes",
			webp: "sponsors/gold/webp/CodingMinutes.webp",
			src: "https://res.cloudinary.com/ds7xs3pq1/image/upload/v1672682312/cm_fcvr7u.jpg",
			url: "https://www.codingminutes.com/",
			id: "silver_8",
		},
			{
				sponsorName: "MLH",
				webp: "sponsors/title/webp/mlh.webp",
				src: "https://res.cloudinary.com/ds7xs3pq1/image/upload/v1672682328/mlhlogo_xi2zyb.png",
				url: "https://mlh.io/",
				id: "title_0",
			},
			{
				sponsorName: "Devfolio",
				webp: "sponsors/title/webp/devfolio.webp",
				src: "https://res.cloudinary.com/ds7xs3pq1/image/upload/v1672682394/devfolio_nukzij.png",
				url: "https://devfolio.co/",
				id: "title_1",
			},
			{
				sponsorName: "Polygon",
				webp: "sponsors/title/webp/polygon.webp",
				src: "https://res.cloudinary.com/ds7xs3pq1/image/upload/v1672682423/polygonlogo_ltkl1w.png",
				url: "https://polygon.technology/",
				id: "title_2",
			},
			{
				sponsorName: "TechAnalogy",
				webp: "sponsors/title/webp/techanalogy.webp",
				src: "https://res.cloudinary.com/ds7xs3pq1/image/upload/v1672682566/techa_aa3goj.jpg",
				url: "https://polygon.technology/",
				id: "title_3",
			},
			{
				sponsorName: "Juspay",
				webp: "sponsors/title/webp/juspay.webp",
				src: "https://res.cloudinary.com/ds7xs3pq1/image/upload/v1672682592/juslogo_pglrve.png",
				url: "https://juspay.in/",
				id: "title_4",
			},
		];
